### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by f0rki** [f0rki/mapping-high-level-constructs-to-llvm-ir#1]
Probably one of the Creative Common variants:
- https://creativecommons.org/licenses/by-sa/4.0/
  - does share-alike impact the use of code snippets?
- https://creativecommons.org/licenses/by/4.0/
- Maybe use CC-0/Public Domain?
- Dual license e.g. with CC-BY-SA and MIT

**Comment by archfrog** [comment]
I think that's a good license.  I usually use the MIT license, but it basically boils down to same as the license you suggest.  I'm all for it :-)

**Comment by f0rki** [comment]
Yeah I also usually use MIT or Apache, but in this case it's more documentation than code so I thought it might be better to license it under something more suitable for text. Wikipedia uses CC-BY-SA and GNU FDL, although I think they had some problems with the latter. So I suggested the CC variants.

@archfrog I think it would be good if you put the licensing terms into the repo, since the content is primarily authored/copyrighted by you.

**Comment by archfrog** [comment]
@f0rki I think you should have the honor of adding the license terms as you are the current maintainer.  At most, I'm just a helping hand, that's how I see it.  Also, you seem to be well aware of what kinds of licenses exist whereas I have simply picked the MIT license some years back because I liked it.

Also, I seem to be unable to find a Markdown version of the rather long CC-SA-4.0, which you may already know where to find.

**Comment by f0rki** [comment]
fixed with commit e684f80
