### ISSUE TITLE
Status of this book

### ISSUE THREAD

**Issue by ceymard** [f0rki/mapping-high-level-constructs-to-llvm-ir#33]
Seeing the dates on the commits makes me think this project is not updated anymore.

Do you have plans in revisiting the subject some time ?
Alternatively, do you know other resources such as this one ? I particularly like the terseness of the examples (compared to the kaleidoscope example).

Cheers

**Comment by f0rki** [comment]
Unfortunately this book is at the low end of my priority list. As I am working more with LLVM again these days I might push some updates soon. 

I do however, try to accept any pull request as quickly as possible ;)

I do not have recommendations regarding similar resources.

**Comment by archfrog** [comment]
The project hasn't been abandoned as such, it is just that none of us have committed in a long while.

I recently abandoned computer gaming, which has been taking up a lot of my time, so there is some hope that I at least will find some time to update this project.

Feel free to write what you'd like to see in particular.  The only thing I doubt I'll ever get around to is "zero cost exception handling" (because I dislike it so much for being extremely expensive when an exception happens).

Thanks for the reminder to continue work on this project, though :-)

@f0rki, would you be willing to document how to publish updates of this project?

**Comment by f0rki** [comment]
> would you be willing to document how to publish updates of this project?

Not sure what you mean? The read-the-docs page is built automatically from the latest commit.

**Comment by archfrog** [comment]
Oh, didn't know that, no worries then :-)

**Comment by ceymard** [comment]
I'd be happy to create pull requests, if only I felt confident with LLVM, which I do not and thus why this resource is so enticing to me.

As things become clearer though, I'd be happy to contribute.

**Comment by f0rki** [comment]
@ceymard even small contributions like fixing typos or even reporting which llvm samples  currently compile or not are greatly appreciated! :)
