### ISSUE TITLE
Inline functions

### ISSUE THREAD

**Issue by tpisto** [f0rki/mapping-high-level-constructs-to-llvm-ir#45]
Would be nice to have examples with function inlining like in C

```
inline int double(int arg1) {
   return arg1 * 2;
}
```

**Comment by f0rki** [comment]
I am wondering whether this would be a good fit for this guide, since inlining is mostly a question of calling the inlining passes and setting function attributes. Is there anything substantial that needs to be done on the LLVM IR level regarding inlining?

Anyways, @tpisto if you just encountered a problem that you think should be covered here, feel free to add a section via a pull request :)
